lowtox_backend/lowtox_backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include('mainwebsite.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
]

lowtox_backend/mainwebsite/urls.py
from django.urls import path, include
from . import views

app_name = 'mainwebsite'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('intro', views.intro_view, name='intro'),
    path('who-can-apply', views.who_can_apply_view, name='who-can-apply'),
    path('financial-support', views.financial_support_view, name='financial-support'),
    path('tasks', views.tasks_view, name='tasks'),
    path('faq', views.faq_view, name='faq'),
    path('apply', views.apply_view, name='apply'),

]

lowtox_backend/polls/urls.py
from django.urls import path, include
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.random_detail_view, name='random'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/skip/', views.skip, name='skip'),
]

lowtox_backend/polls/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import UniqueConstraint


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    label = models.CharField(max_length=200, blank=True, null=True, default=None)  # Label for number & text questions
    NUMBER = 'NB'
    TEXT = 'TXT'
    ONE_ANSWER = 'ONE'
    MULTIPLE_ANSWER = 'MULTI'
    QUESTIONS_TYPES = [
        (NUMBER, 'Number'),
        (TEXT, 'Text'),
        (ONE_ANSWER, 'One Answer'),
        (MULTIPLE_ANSWER, 'Multiple Answers'),
    ]
    type = models.CharField(max_length=5, choices=QUESTIONS_TYPES, default=ONE_ANSWER)

    def __str__(self):
        return self.question_text

    def is_text(self):
        return self.type == self.TEXT

    def is_number(self):
        return self.type == self.NUMBER

    def is_one_answer(self):
        return self.type == self.ONE_ANSWER

    def is_multiple_answer(self):
        return self.type == self.MULTIPLE_ANSWER


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.choice_text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer_open = models.CharField(max_length=1000)
    choice = models.ManyToManyField(Choice)
    skipped = models.BooleanField(default=False)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['question', 'user'], name='unique answer')
        ]

    def __str__(self):
        if self.question.is_number() or self.question.is_text():
            return self.answer_open
        else:
            return ''

    def get_answer(self):
        if self.skipped:
            return 'Skipped'
        if self.question.is_text() or self.question.is_number():
            return self.answer_open
        elif self.question.is_one_answer() or self.question.is_multiple_answer():
            return [c.choice_text for c in self.choice.all()]


class UserData(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        null=True,
    )

lowtox_backend/polls/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
import random

from .models import Choice, Question, User, Answer, UserData


@login_required
def random_detail_view(request):
    user = auth.get_user(request)

    # retrieve the user's data
    if not hasattr(user, 'userdata'):
        # If it doesn't exist create it
        ud = UserData(user=user)
        ud.save()

    # get userdata__question
    question = user.userdata.question
    print(question)
    if(question):
        # if it exist return this question:
        context = {'question': question}
        return render(request, 'polls/random.html', context)
    else:
        # else return random question
        # get all questions answered by the user
        answered_questions = Question.objects.filter(answer__user__username=user.username)
        # get all questions unanswered by the user
        unanswered_questions = Question.objects.all().difference(answered_questions)
        # select a random one to display
        if len(unanswered_questions) > 0:
            rand = random.randint(0, len(unanswered_questions) - 1)
            q = unanswered_questions[rand]
            # store the question in the user's data
            user.userdata.question = q
            user.userdata.save()
            context = {'question': q}
            return render(request, 'polls/random.html', context)
        else:
            return render(request, 'polls/random.html')


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    user = auth.get_user(request)
    if question.is_one_answer():
        return _handle_one_answer(question, user, request)
    elif question.is_multiple_answer():
        return _handle_multiple_answers(question, user, request)
    elif question.is_text() or question.is_number():
        return _handle_open_answer(question, user, request)


def _handle_one_answer(question, user, request):
    try:
        selected_choice = question.choice_set.get(pk=request.POST['answer'])
    except (KeyError, Choice.DoesNotExist):
        return HttpResponseRedirect(reverse('polls:random'))
    else:
        answer = Answer(question=question, user=user)
        answer.save()
        answer.choice.add(selected_choice)
        answer.save()
        user.userdata.question = None
        user.userdata.save()
        return HttpResponseRedirect(reverse('polls:random'))


def _handle_multiple_answers(question, user, request):
    selected_choices = question.choice_set.filter(pk__in=request.POST.getlist('answer'))
    if len(selected_choices) == 0:
        return HttpResponseRedirect(reverse('polls:random'))
    else:
        answer = Answer(question=question, user=user)
        answer.save()
        for selected_choice in selected_choices:
            answer.choice.add(selected_choice)
        answer.save()
        user.userdata.question = None
        user.userdata.save()
        return HttpResponseRedirect(reverse('polls:random'))


def _handle_open_answer(question, user, request):
    answer_open = request.POST['answer']
    if not answer_open:
        return HttpResponseRedirect(reverse('polls:random'))
    else:
        answer = Answer(question=question, user=user, answer_open=answer_open)
        answer.save()
        user.userdata.question = None
        user.userdata.save()
        return HttpResponseRedirect(reverse('polls:random'))


def skip(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    user = auth.get_user(request)
    answer = Answer(question=question, user=user, skipped=True)
    answer.save()
    user.userdata.question = None
    user.userdata.save()
    return HttpResponseRedirect(reverse('polls:random'))

lowtox_backend/polls/templates/polls/_includes/footer_mail.html
<!-- Footer -->
<footer class="footer mt-auto pt-3 bg-orange">
  <div class="container">
    <!-- Begin Mailchimp Signup Form -->
    <div id="mc_embed_signup">
      <form action="https://miernik.us3.list-manage.com/subscribe/post?u=0c0ecddb615d9ea799d1a5068&amp;id=5465751e05" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
	<div id="mc_embed_signup_scroll">
	  <h2>Enter an email address to receive more information</h2>
	  <div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
	  <div class="mc-field-group">
	    <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
	    </label>
	    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
	  </div>
	  <div id="mce-responses" class="clear">
	    <div class="response" id="mce-error-response" style="display:none"></div>
	    <div class="response" id="mce-success-response" style="display:none"></div>
	  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	  <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_0c0ecddb615d9ea799d1a5068_5465751e05" tabindex="-1" value=""></div>
	  <div class="clear"><input type="submit" value="Subscribe" name="subscribe" class="btn btn-primary"></div>
	</div>
      </form>
    </div>
  </div>
  <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
  <!--End mc_embed_signup-->


</footer>

lowtox_backend/polls/templates/polls/_includes/head.html
{% load static %}
{% load sass_tags %}
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{{title}}</title>
  <meta name="description" content="{% block description %}Building a low toxicity world{% endblock %}">
  <!--[if lte IE 8]><script src="{% static 'mainwebsite/js/ie/html5shiv.js' %}"></script><![endif]-->
  <link rel="canonical" href="{% url 'mainwebsite:index'%}">
  <link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% sass_src 'mainwebsite/css/main.scss' %}"/>
  <!--[if lte IE 8]><link rel="stylesheet" href="{% static 'mainwebsite/css/ie8.css' %}" /><![endif]-->
  <!--[if lte IE 9]><link rel="stylesheet" href="{% static 'mainwebsite/css/ie9.css' %}" /><![endif]-->
  <link rel="alternate" type="application/rss+xml" title="Lowtox.org" href="{% static '/feed.xml' %}">

  <meta property="og:title" content="{{title}}"/>
  <meta property="og:image" content="https://lowtox.org/images/facebook-share-thumbnail.jpg"/>
  <meta property="og:site_name" content="{{title}}"/>
  <meta property="og:description" content="{{description}}"/>
  <meta name="google-site-verification" content="CnuZBRzGaeUnjLJugxizRFuz3a10Xw5Y6kVHWLASIAE" />
  <link rel="icon" href="./favicon.ico?v=3" />

  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@lowtox">
  <meta name="twitter:creator" content="@lowtox">
  <meta name="twitter:title" content="lowtox.org">
  <meta name="twitter:description" content="Supporting Low-tox living">
  <meta name="twitter:image" content="https://lowtox.org/images/twitter-card-ratio.jpg">
</head>

lowtox_backend/polls/templates/polls/_includes/header.html
{% load static %}
<!-- Header -->
<header id="header" class="bg-primary">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
            <div class="row">
                <div class="col-md-5 text-center">
                    <a class="navbar-brand" href="{% url 'mainwebsite:index' %}"><img src="{% static 'mainwebsite/images/logo_white_text.png' %}"></a>
                </div>
                <div class="col-md-7">
                </div>

                <!--<div class="col-md-7">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            <a class="btn btn-light btn-header" href="{% url 'mainwebsite:index' %}">Home</a>
                            <a class="btn btn-light btn-header" href="{% url 'mainwebsite:intro' %}">Intro</a>
                            <a class="btn btn-light btn-header" href="{% url 'mainwebsite:who-can-apply' %}">Who can apply ?</a>
                            <a class="btn btn-light btn-header" href="{% url 'mainwebsite:financial-support' %}">Financial Support</a>
                            <a class="btn btn-light btn-header" href="{% url 'mainwebsite:tasks' %}">Tasks</a>
                            <a class="btn btn-light btn-header" href="{% url 'mainwebsite:faq' %}">FAQ</a>
                            <a class="btn btn-light btn-header" href="{% url 'mainwebsite:apply' %}">Apply</a>
                        </div>
                    </div>
                </div>-->
            </div>
        </div>
    </nav>
</header>

lowtox_backend/polls/templates/polls/_includes/scripts.html
{% load static %}

<!-- Scripts -->
<script src="{% static 'mainwebsite/js/jquery.min.js' %}"></script>
<script src="{% static 'mainwebsite/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'mainwebsite/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'mainwebsite/js/skel.min.js' %}"></script>
<script src="{% static 'mainwebsite/js/util.js' %}"></script>
<!--[if lte IE 8]><script src="{% static 'mainwebsite/js/ie/respond.min.js' %}"></script><![endif]-->
<script src="{% static 'mainwebsite/js/main.js' %}"></script>
<script src="{% static 'mainwebsite/js/particles-dan.js' %}"></script>
<!--<script src="https://checkout.stripe.com/checkout.js"></script> --><!-- saving some bandwidth by puttin only in 'investment' -->
<!--<script src="{% static 'mainwebsite/js/payments.js' %}"></script>-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>



<script>
      $(document).ready(function() {
	$(".navbar").find(".active").removeClass("active");
	$('a[href="' + location.pathname + '"]').addClass('active');
      });
    </script>

<!--
  <script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-91031171-1', 'auto');
ga('send', 'pageview');

  </script>
  -->

<!-- Matomo -->
<!--<script type="text/javascript">
	var _paq = window._paq || [];
/* tracker methods like "setCustomDimension" should be called before "trackPageView" */
_paq.push(['trackPageView']);
_paq.push(['enableLinkTracking']);
(function() {
  var u="//matomo.1312.media/";
  _paq.push(['setTrackerUrl', u+'matomo.php']);
  _paq.push(['setSiteId', '3']);
  var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
  g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
})();
      </script> -->
<!-- End Matomo Code -->

<!-- <script type="text/javascript">
var vsid = "sa54700";
(function() {
(function() {
var vsjs = document.createElement('script'); vsjs.type = 'text/javascript'; vsjs.async = true; vsjs.setAttribute('defer', 'defer');
vsjs.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'www.virtualspirits.com/vsa/chat-'+vsid+'.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(vsjs, s);
})();
</script> -->