lowtox_backend/lowtox_backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include('mainwebsite.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
]

lowtox_backend/polls/urls.py
from django.urls import path, include
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.random_detail_view, name='random'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/skip/', views.skip, name='skip'),
]

lowtox_backend/polls/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import UniqueConstraint


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    label = models.CharField(max_length=200, blank=True, null=True, default=None)  # Label for number & text questions
    NUMBER = 'NB'
    TEXT = 'TXT'
    ONE_ANSWER = 'ONE'
    MULTIPLE_ANSWER = 'MULTI'
    QUESTIONS_TYPES = [
        (NUMBER, 'Number'),
        (TEXT, 'Text'),
        (ONE_ANSWER, 'One Answer'),
        (MULTIPLE_ANSWER, 'Multiple Answers'),
    ]
    type = models.CharField(max_length=5, choices=QUESTIONS_TYPES, default=ONE_ANSWER)

    def __str__(self):
        return self.question_text

    def is_text(self):
        return self.type == self.TEXT

    def is_number(self):
        return self.type == self.NUMBER

    def is_one_answer(self):
        return self.type == self.ONE_ANSWER

    def is_multiple_answer(self):
        return self.type == self.MULTIPLE_ANSWER


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.choice_text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer_open = models.CharField(max_length=1000)
    choice = models.ManyToManyField(Choice)
    skipped = models.BooleanField(default=False)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['question', 'user'], name='unique answer')
        ]

    def __str__(self):
        if self.question.is_number() or self.question.is_text():
            return self.answer_open
        else:
            return ''

    def get_answer(self):
        if self.skipped:
            return 'Skipped'
        if self.question.is_text() or self.question.is_number():
            return self.answer_open
        elif self.question.is_one_answer() or self.question.is_multiple_answer():
            return [c.choice_text for c in self.choice.all()]


class UserData(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        null=True,
    )

lowtox_backend/polls/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
import random

from .models import Choice, Question, User, Answer, UserData


@login_required
def random_detail_view(request):
    user = auth.get_user(request)

    # retrieve the user's data
    if not hasattr(user, 'userdata'):
        # If it doesn't exist create it
        ud = UserData(user=user)
        ud.save()

    # get userdata__question
    question = user.userdata.question
    print(question)
    if(question):
        # if it exist return this question:
        context = {'question': question}
        return render(request, 'polls/random.html', context)
    else:
        # else return random question
        # get all questions answered by the user
        answered_questions = Question.objects.filter(answer__user__username=user.username)
        # get all questions unanswered by the user
        unanswered_questions = Question.objects.all().difference(answered_questions)
        # select a random one to display
        if len(unanswered_questions) > 0:
            rand = random.randint(0, len(unanswered_questions) - 1)
            q = unanswered_questions[rand]
            # store the question in the user's data
            user.userdata.question = q
            user.userdata.save()
            context = {'question': q}
            return render(request, 'polls/random.html', context)
        else:
            return render(request, 'polls/random.html')


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    user = auth.get_user(request)
    if question.is_one_answer():
        return _handle_one_answer(question, user, request)
    elif question.is_multiple_answer():
        return _handle_multiple_answers(question, user, request)
    elif question.is_text() or question.is_number():
        return _handle_open_answer(question, user, request)


def _handle_one_answer(question, user, request):
    try:
        selected_choice = question.choice_set.get(pk=request.POST['answer'])
    except (KeyError, Choice.DoesNotExist):
        return HttpResponseRedirect(reverse('polls:random'))
    else:
        answer = Answer(question=question, user=user)
        answer.save()
        answer.choice.add(selected_choice)
        answer.save()
        user.userdata.question = None
        user.userdata.save()
        return HttpResponseRedirect(reverse('polls:random'))


def _handle_multiple_answers(question, user, request):
    selected_choices = question.choice_set.filter(pk__in=request.POST.getlist('answer'))
    if len(selected_choices) == 0:
        return HttpResponseRedirect(reverse('polls:random'))
    else:
        answer = Answer(question=question, user=user)
        answer.save()
        for selected_choice in selected_choices:
            answer.choice.add(selected_choice)
        answer.save()
        user.userdata.question = None
        user.userdata.save()
        return HttpResponseRedirect(reverse('polls:random'))


def _handle_open_answer(question, user, request):
    answer_open = request.POST['answer']
    if not answer_open:
        return HttpResponseRedirect(reverse('polls:random'))
    else:
        answer = Answer(question=question, user=user, answer_open=answer_open)
        answer.save()
        user.userdata.question = None
        user.userdata.save()
        return HttpResponseRedirect(reverse('polls:random'))


def skip(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    user = auth.get_user(request)
    answer = Answer(question=question, user=user, skipped=True)
    answer.save()
    user.userdata.question = None
    user.userdata.save()
    return HttpResponseRedirect(reverse('polls:random'))

lowtox_backend/polls/templates/polls/random.html
<!--suppress XmlDuplicatedId -->
{% extends 'polls/_layouts/page.html' %}

{% block title %}Questions{% endblock %}

{% block content %}
<br />
<main role="main">
    <div class="container">
        {% if not question %}
        <h1>You have answered all questions, thank you.</h1>
        {% else %}
        <h1>{{ question.question_text }}</h1>

        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% if question.is_number %}
            <div class="form-group">
                <input id="input" name="answer" class="form-control" type="number" value="" required>
                {% if question.label %}
                <label for="input">{{ question.label }}</label>
                {% endif %}
            </div>
            {% endif %}

            {% if question.is_text %}
            <div class="form-group">
                {% if question.label %}
                <label for="input">{{ question.label }}</label>
                {% endif %}
                <textarea id="input" name="answer" value="" class="form-control" required></textarea>
            </div>
            {% endif %}

            {% if question.is_one_answer %}
            <div class="form-check">
                {% for choice in  question.choice_set.all %}
                <input class="form-check-input" type="radio" name="answer" id="choice{{ forloop.counter }}" class="custom-control-input" value="{{ choice.id }}" required>
                <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </div>
            {% endif %}

            {% if question.is_multiple_answer %}
            <div class="form-check">
                {% for choice in  question.choice_set.all %}
                <input class="form-check-input" type="checkbox" name="answer" id="choice{{ forloop.counter }}" class="form-control" value="{{ choice.id }}">
                <label class="form-check-label" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </div>
            {% endif %}

            <br>
            <input type="submit" value="Vote">
        </form>
        <form action="{% url 'polls:skip' question.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Skip">
        </form>
        {% endif %}
    </div>
</main>
{% endblock %}